name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter


  english_words: ^4.0.0
  provider: ^6.0.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  firebase_ui_auth: ^1.14.0
  google_sign_in: ^6.2.1
  firebase_ui_oauth_google: ^1.3.2
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  http: ^1.2.1
  json_annotation: ^4.9.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  google_generative_ai: ^0.4.3
  dotenv: ^4.2.0
  flip_card: ^0.7.0
  flutter_card_swiper: ^7.0.1
  card_swiper: ^3.0.1
  path_provider: ^2.1.3
  image_downloader:
    git:
      url: https://github.com/VikasTailorbird/image_downloader
  flutter_dotenv: ^5.1.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  flutter_spinkit: ^5.2.1
  firebase_storage: ^11.7.7
  cloud_firestore: ^4.17.5
  syncfusion_flutter_calendar: ^26.1.40+1
  syncfusion_flutter_charts: ^26.1.40
  flutter_heatmap_calendar: ^1.0.5
  image_picker: ^1.1.2
  uuid: ^4.4.0
  permission_handler: ^11.3.1
  maps_launcher: ^2.2.1
  logger: ^2.3.0
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - .env
