// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9KA-yloPLl9KXEFwAad04Mavy-bOapkA',
    appId: '1:850910294528:web:c8f8f5d485d7c207501ee5',
    messagingSenderId: '850910294528',
    projectId: 'gemai-app',
    authDomain: 'gemai-app.firebaseapp.com',
    storageBucket: 'gemai-app.appspot.com',
    measurementId: 'G-72Y81735M4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwgto0x1-QrVNomLBDxRjXXjCl90XHeR4',
    appId: '1:850910294528:android:256124fc977fd531501ee5',
    messagingSenderId: '850910294528',
    projectId: 'gemai-app',
    storageBucket: 'gemai-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNOkM0taeBMcZ5SgppxcWWRc-pEJhKKpE',
    appId: '1:850910294528:ios:d73aa45f7b0a928d501ee5',
    messagingSenderId: '850910294528',
    projectId: 'gemai-app',
    storageBucket: 'gemai-app.appspot.com',
    iosBundleId: 'com.example.scavhunt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNOkM0taeBMcZ5SgppxcWWRc-pEJhKKpE',
    appId: '1:850910294528:ios:d73aa45f7b0a928d501ee5',
    messagingSenderId: '850910294528',
    projectId: 'gemai-app',
    storageBucket: 'gemai-app.appspot.com',
    iosBundleId: 'com.example.scavhunt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9KA-yloPLl9KXEFwAad04Mavy-bOapkA',
    appId: '1:850910294528:web:df599be5ba28df23501ee5',
    messagingSenderId: '850910294528',
    projectId: 'gemai-app',
    authDomain: 'gemai-app.firebaseapp.com',
    storageBucket: 'gemai-app.appspot.com',
    measurementId: 'G-W5HXNBHDZN',
  );

}